apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ds-web-dev
  namespace: sit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ds-web-dev
    spec:
      containers:
        - name: ds-web-dev
          image: registry.cn-beijing.aliyuncs.com/bmwpoc/ds-web-dev:{version}
          ports:
            - name: http-port
              containerPort: 80
      imagePullSecrets:
        - name: bmwpoc